name: nanocaller
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.5=py310h2372a71_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.9=hd590300_0
  - amply=0.1.6=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - bcftools=1.17=h3cc50cf_1
  - biopython=1.81=py310h2372a71_1
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - brotlipy=0.7.0=py310h2372a71_1006
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.16.0=hbbf8b49_1016
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2fee648_5
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cmake=3.27.4=hcfe8598_4
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=41.0.3=py310h75e40e8_0
  - docutils=0.20.1=py310hff52083_3
  - eigen=3.2.8=2
  - expat=2.5.0=hcb278e6_1
  - flatbuffers=23.5.26=h59595ed_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.0=py310h2372a71_1
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.21.1=h27087fc_0
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.1=h0b41bf4_3
  - google-auth=2.22.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - graphite2=1.3.13=h59595ed_1003
  - grpcio=1.54.3=py310heca2aa9_0
  - gsl=2.7=he838d99_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.9.0=nompi_py310ha2ad45a_103
  - harfbuzz=7.3.0=hdb3a94d_0
  - hdf5=1.14.2=nompi_h4f84152_100
  - hpack=4.0.0=pyh9f0ad1d_0
  - htslib=1.17=h81da01d_2
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - isa-l=2.30.0=hd590300_6
  - jax=0.4.14=pyhd8ed1ab_1
  - jaxlib=0.4.14=cpu_py310h67d73b5_1
  - jsoncpp=1.9.5=h4bd325d_1
  - keras=2.12.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.0.6=hcb278e6_1
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=19_linux64_openblas
  - libcblas=3.9.0=19_linux64_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.2.1=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=13.1.0=he5830b7_0
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=3.0.0=1
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.4=hebfc3b9_0
  - libgomp=13.1.0=he5830b7_0
  - libgrpc=1.54.3=hb20ce57_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=19_linux64_openblas
  - liblapacke=3.9.0=19_linux64_openblas
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=hd590300_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsqlite=3.43.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.1=h8b53f26_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - markdown=3.4.4=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h2372a71_1
  - mdurl=0.1.2=pyhd8ed1ab_0
  - ml_dtypes=0.2.0=py310hcc13569_2
  - multidict=6.0.4=py310h2372a71_1
  - muscle=3.8.1551=h7d875b9_6
  - namex=0.0.8=pyhd8ed1ab_0
  - nanocaller=3.4.1=hdfd78af_0
  - ncurses=6.4.20240210=h59595ed_0
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.25.2=py310ha4c1d20_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjdk=20.0.0=h8e330f5_0
  - openssl=3.1.2=hd590300_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - optree=0.12.1=py310haa687a3_0
  - packaging=23.1=pyhd8ed1ab_0
  - parasail-python=1.3.4=py310hdf79db3_2
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=7_hd590300_perl5
  - pigz=2.6=h2797004_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - pooch=1.7.0=pyhd8ed1ab_4
  - protobuf=4.21.12=py310heca2aa9_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.7.0=py310hff52083_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyfaidx=0.7.2.1=pyh7cba7a3_1
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysam=0.21.0=py310h41dec4a_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.12=hd12c33a_0_cpython
  - python-flatbuffers=23.5.26=pyhd8ed1ab_0
  - python-isal=1.2.0=py310h2372a71_0
  - python-zlib-ng=0.5.0=py310h6420a16_0
  - python_abi=3.10=4_cp310
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rhash=1.4.4=hd590300_0
  - rich=13.8.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - rtg-tools=3.12.1=hdfd78af_0
  - samtools=1.17=hd87286a_2
  - scipy=1.11.2=py310hb13e2d6_1
  - setuptools=68.1.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hdb0a2a9_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - tabixpp=1.1.2=hd68fcf3_1
  - tensorboard=2.12.3=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h34c0648_0
  - tensorflow=2.12.1=cpu_py310hd1aba9c_0
  - tensorflow-base=2.12.1=cpu_py310h57e0714_0
  - tensorflow-estimator=2.12.1=cpu_py310haacee6a_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vcflib=1.0.9=h146fbdb_3
  - werkzeug=2.3.7=pyhd8ed1ab_0
  - wfa2-lib=2.3.3=h4ac6f70_2
  - wget=1.20.3=ha35d2d1_1
  - whatshap=2.0=py310h0dbaff4_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h2372a71_1
  - xopen=1.7.0=py310hff52083_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yarl=1.9.2=py310h2372a71_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zlib-ng=2.2.1=he02047a_0
  - zstandard=0.19.0=py310h5764c6d_0
  - zstd=1.5.5=hfc55251_0
