channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _tflow_select=2.3.0=mkl
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.5=py38h01eb140_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - bcftools=1.12=h45bccc9_1
  - biopython=1.81=py38h01eb140_1
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py38h6d47a40_5
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.6=h6f57e76_1
  - coin-or-clp=1.17.7=h256e9bb_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - cryptography=39.0.0=py38h1724139_0
  - docutils=0.20.1=py38h578d9bd_3
  - frozenlist=1.4.0=py38h01eb140_1
  - gast=0.3.3=py_0
  - google-auth=2.17.3=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - grpcio=1.51.1=py38h7dc2bf5_0
  - gsl=2.6=he838d99_2
  - h5py=2.10.0=nompi_py38h9915d05_106
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - htslib=1.12=h9093b5e_1
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - isa-l=2.30.0=hd590300_6
  - k8=0.2.5=hdcf5f25_4
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libabseil=20220623.0=cxx17_h05df665_6
  - libblas=3.9.0=19_linux64_openblas
  - libcblas=3.9.0=19_linux64_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_13
  - libgfortran-ng=13.2.0=h69a702a_13
  - libgfortran5=13.2.0=h3d2ce59_13
  - libgomp=13.2.0=h77fa898_13
  - libgrpc=1.51.1=h05bd8bd_0
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=19_linux64_openblas
  - liblapacke=3.9.0=19_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=hd590300_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libprotobuf=3.21.12=hfc55251_2
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=hc0a3c3a_13
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - mappy=2.26=py38h7cf9df2_1
  - markdown=3.4.4=pyhd8ed1ab_0
  - markupsafe=2.1.3=py38h01eb140_1
  - medaka=1.4.4=py38h130def0_0
  - minimap2=2.26=he4a0461_2
  - multidict=6.0.4=py38h01eb140_1
  - ncurses=6.2=h58526e2_4
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.19.5=py38h8246c76_3
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - ont-fast5-api=4.1.1=pyhdfd78af_0
  - openssl=1.1.1v=hd590300_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - packaging=23.1=pyhd8ed1ab_0
  - parasail-python=1.3.4=py38h40d3509_2
  - pbzip2=1.1.13=h1fcc475_2
  - perl=5.32.1=7_hd590300_perl5
  - pigz=2.6=h2797004_1
  - pip=23.2.1=pyhd8ed1ab_0
  - progressbar33=2.4=py_0
  - protobuf=4.21.12=py38h8dc9893_0
  - pulp=2.7.0=py38h578d9bd_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyfaidx=0.7.2.1=pyh7cba7a3_1
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysam=0.21.0=py38h1c8baaf_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pyspoa=0.0.10=py38he0f268d_1
  - python=3.8.12=hb7a2778_2_cpython
  - python-edlib=1.3.9=py38h2123bcc_8
  - python-isal=1.2.0=py38h01eb140_0
  - python_abi=3.8=4_cp38
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - racon=1.5.0=hdcf5f25_4
  - re2=2022.06.01=h27087fc_1
  - readline=8.1=h46c0cb4_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - samtools=1.12=h9aed4be_1
  - scipy=1.9.1=py38hea3f02b_0
  - setuptools=68.1.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.37.0=h9cd32fc_0
  - tar=1.34=hb2e2bae_1
  - tensorboard=2.14.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38h52d8a92_0
  - tensorflow=2.2.0=mkl_py38h6d3daf0_0
  - tensorflow-base=2.2.0=mkl_py38h5059a2d_0
  - tensorflow-estimator=2.6.0=py38h709712a_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - werkzeug=2.3.7=pyhd8ed1ab_0
  - whatshap=2.0=py38h2494328_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - wrapt=1.15.0=py38h01eb140_1
  - xopen=1.7.0=py38h578d9bd_3
  - xz=5.2.6=h166bdaf_0
  - yarl=1.9.2=py38h01eb140_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.5=hfc55251_0
