contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #cyptyper channel"
    url: https://nfcore.slack.com/channels/cyptyper
    about: Discussion about the nf-core/cyptyper pipeline
